---
apiVersion: v1
kind: Namespace
metadata:
  name: releasepipeline-scenario-user
---
apiVersion: v1
kind: Namespace
metadata:
  name: releasepipeline-scenario-managed
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleaseLink
metadata:
  name: test-releaselink-user
  namespace: releasepipeline-scenario-user
spec:
  displayName: a test user releaselink
  application: test
  target: releasepipeline-scenario-managed
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleaseLink
metadata:
  name: test-releaselink-managed
  namespace: releasepipeline-scenario-managed
spec:
  displayName: a test managed releaselink
  application: test
  target: releasepipeline-scenario-user
  releaseStrategy: test-strategy
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleaseStrategy
metadata:
  name: test-strategy
  namespace: releasepipeline-scenario-managed
spec:
  pipeline: missing-release-pipeline
  bundle: quay.io/hacbs-release/m4:0.1-alpine
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: test-release
  namespace: releasepipeline-scenario-user
spec:
  releaseLink: test-releaselink-user
  component: test
