---
apiVersion: v1
kind: Namespace
metadata:
  name: targeting-itself
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleaseLink
metadata:
  name: targets-itself
  namespace: targeting-itself
spec:
  displayName: a circular releaselink which targets its own workspace
  application: test
  target: targeting-itself
