package agent_models

import (
	"os"
	"strings"
)

var envMap = map[string]interface{}{
	"BUILD_NUMBER":                                nil,
	"BUILD_ID":                                    nil,
	"BUILD_URL":                                   nil,
	"NODE_NAME":                                   nil,
	"JOB_NAME":                                    nil,
	"BUILD_TAG":                                   nil,
	"JENKINS_URL":                                 nil,
	"WORKSPACE":                                   nil,
	"GIT_COMMIT":                                  nil,
	"GIT_URL":                                     nil,
	"GIT_BRANCH":                                  nil,
	"TEAMCITY_VERSION":                            nil,
	"TEAMCITY_PROJECT_NAME":                       nil,
	"TEAMCITY_BUILDCONF_NAME":                     nil,
	"TEAMCITY_BUILD_IS_PERSONAL":                  nil,
	"TEAMCITY_BUILD_PROPERTIES_FILE":              nil,
	"CIRCLE_BRANCH":                               nil,
	"CIRCLE_BUILD_NUM":                            nil,
	"CIRCLE_BUILD_URL":                            nil,
	"CIRCLE_JOB":                                  nil,
	"CIRCLE_NODE_INDEX":                           nil,
	"CIRCLE_NODE_TOTAL":                           nil,
	"CIRCLE_PR_NUMBER":                            nil,
	"CIRCLE_PR_REPONAME":                          nil,
	"CIRCLE_PULL_REQUEST":                         nil,
	"CIRCLE_PULL_REQUESTS":                        nil,
	"CIRCLE_REPOSITORY_URL":                       nil,
	"CIRCLE_SHA1":                                 nil,
	"CIRCLE_TAG":                                  nil,
	"CIRCLE_WORKFLOW_ID":                          nil,
	"CIRCLE_WORKFLOW_JOB_ID":                      nil,
	"CIRCLE_WORKFLOW_WORKSPACE_ID":                nil,
	"CIRCLE_WORKING_DIRECTORY":                    nil,
	"CI_BUILDS_ID":                                nil,
	"CI_COMMIT_AUTHOR":                            nil,
	"CI_COMMIT_BEFORE_SHA":                        nil,
	"CI_COMMIT_BRANCH":                            nil,
	"CI_COMMIT_DESCRIPTION":                       nil,
	"CI_COMMIT_MESSAGE":                           nil,
	"CI_COMMIT_REF_NAME":                          nil,
	"CI_COMMIT_SHORT_SHA":                         nil,
	"CI_COMMIT_SHA":                               nil,
	"CI_COMMIT_TAG":                               nil,
	"CI_COMMIT_TITLE":                             nil,
	"CI_COMMIT_TIMESTAMP":                         nil,
	"CI_CONCURRENT_ID":                            nil,
	"CI_CONCURRENT_PROJECT_ID":                    nil,
	"CI_CONFIG_PATH":                              nil,
	"CI_DEFAULT_BRANCH":                           nil,
	"CI_DEPENDENCY_PROXY_SERVER":                  nil,
	"CI_DISPOSABLE_ENVIRONMENT":                   nil,
	"CI_ENVIRONMENT_NAME":                         nil,
	"CI_ENVIRONMENT_SLUG":                         nil,
	"CI_ENVIRONMENT_URL":                          nil,
	"CI_ENVIRONMENT_ACTION":                       nil,
	"CI_ENVIRONMENT_TIER":                         nil,
	"CI_JOB_ID":                                   nil,
	"CI_JOB_NAME":                                 nil,
	"CI_JOB_STAGE":                                nil,
	"CI_JOB_IMAGE":                                nil,
	"CI_JOB_URL":                                  nil,
	"CI_JOB_STARTED_AT":                           nil,
	"CI_KUBERNETES_ACTIVE":                        nil,
	"CI_NODE_INDEX":                               nil,
	"CI_NODE_TOTAL":                               nil,
	"CI_PIPELINE_URL":                             nil,
	"CI_PIPELINE_DIR":                             nil,
	"CI_PROJECT_DIR":                              nil,
	"CI_PROJECT_NAME":                             nil,
	"CI_PROJECT_NAMESPACE":                        nil,
	"CI_PROJECT_PATH":                             nil,
	"CI_PROJECT_PATH_SLUG":                        nil,
	"CI_PROJECT_REPOSITORY_LANGUAGES":             nil,
	"CI_PROJECT_ROOT_NAMESPACE":                   nil,
	"CI_PROJECT_TITLE":                            nil,
	"CI_PROJECT_URL":                              nil,
	"CI_PROJECT_DESCRIPTION":                      nil,
	"CI_REGISTRY_IMAGE":                           nil,
	"CI_REPOSITORY_URL":                           nil,
	"CI_SERVER_HOST":                              nil,
	"CI_SERVER_NAME":                              nil,
	"CI_SERVER_URL":                               nil,
	"CI_SERVER_VERSION_MAJOR":                     nil,
	"CI_SERVER_VERSION_MINOR":                     nil,
	"CI_SERVER_VERSION_PATCH":                     nil,
	"CI_SERVER_VERSION":                           nil,
	"GITLAB_CI":                                   nil,
	"CI_MERGE_REQUEST_APPROVED":                   nil,
	"CI_MERGE_REQUEST_ASSIGNEES":                  nil,
	"CI_MERGE_REQUEST_ID":                         nil,
	"CI_MERGE_REQUEST_IID":                        nil,
	"CI_MERGE_REQUEST_PROJECT_ID":                 nil,
	"CI_MERGE_REQUEST_PROJECT_PATH":               nil,
	"CI_MERGE_REQUEST_PROJECT_URL":                nil,
	"CI_MERGE_REQUEST_REFS_PATH":                  nil,
	"CI_MERGE_REQUEST_LABELS":                     nil,
	"CI_MERGE_REQUEST_MILESTONE":                  nil,
	"CI_MERGE_REQUEST_SOURCE_BRANCH_NAME":         nil,
	"CI_MERGE_REQUEST_SOURCE_BRANCH_SHA":          nil,
	"CI_MERGE_REQUEST_SOURCE_PROJECT_ID":          nil,
	"CI_MERGE_REQUEST_SOURCE_PROJECT_PATH":        nil,
	"CI_MERGE_REQUEST_SOURCE_PROJECT_URL":         nil,
	"CI_MERGE_REQUEST_TARGET_BRANCH_NAME":         nil,
	"CI_MERGE_REQUEST_TARGET_BRANCH_SHA":          nil,
	"CI_MERGE_REQUEST_TITLE":                      nil,
	"CI_MERGE_REQUEST_EVENT_TYPE":                 nil,
	"CI_MERGE_REQUEST_DIFF_ID":                    nil,
	"CI_MERGE_REQUEST_DIFF_BASE_SHA":              nil,
	"CI_EXTERNAL_PULL_REQUEST_IID":                nil,
	"CI_EXTERNAL_PULL_REQUEST_SOURCE_REPOSITORY":  nil,
	"CI_EXTERNAL_PULL_REQUEST_TARGET_REPOSITORY":  nil,
	"CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME": nil,
	"CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_NAME": nil,
	"CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_SHA":  nil,
	"CI_EXTERNAL_PULL_REQUEST_TARGET_BRANCH_SHA":  nil,
	"CI":                       nil,
	"GITHUB_ACTION":            nil,
	"GITHUB_ACTION_PATH":       nil,
	"GITHUB_ACTION_REPOSITORY": nil,
	"GITHUB_BASE_REF":          nil,
	"GITHUB_ENV":               nil,
	"GITHUB_HEAD_REF":          nil,
	"GITHUB_JOB":               nil,
	"GITHUB_PATH":              nil,
	"GITHUB_REF":               nil,
	"GITHUB_REF_NAME":          nil,
	"GITHUB_REF_TYPE":          nil,
	"GITHUB_REPOSITORY":        nil,
	"GITHUB_REPOSITORY_OWNER":  nil,
	"GITHUB_SHA":               nil,
	"GITHUB_STEP_SUMMARY":      nil,
	"GITHUB_WORKFLOW":          nil,
	"GITHUB_WORKSPACE":         nil,
	"RUNNER_OS":                nil,
	"RUNNER_TEMP":              nil,
	"RUNNER_ARCH":              nil,
	"RUNNER_NAME":              nil,
	"RUNNER_TOOL_CACHE":        nil,
}

func getEnvVarToMap() map[string]string {
	foundEnvMap := map[string]string{}
	for _, envVar := range os.Environ() {
		if _, ok := envMap[strings.ToUpper(envVar)]; ok {
			foundEnvMap[strings.ToUpper(envVar)] = os.Getenv(envVar)
		}
	}
	envVars := os.Environ()
	for _, env := range envVars {
		// Split each environment variable into key and value
		pair := strings.SplitN(env, "=", 2)

		// Check if the key starts with SEALIGHTS
		if strings.HasPrefix(pair[0], "SEALIGHTS") {
			// Add to our map if it matches the prefix
			foundEnvMap[pair[0]] = pair[1]
		}
	}
	return foundEnvMap
}
