apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleaseLink
metadata:
  name: demo
  namespace: demo
spec:
  displayName: Users's ReleaseLink
  application: m4-app
  target: managed
---
apiVersion: appstudio.redhat.com/v1alpha1
kind: ReleaseLink
metadata:
  name: managed
  namespace: managed
spec:
  displayName: Managed Workspace's ReleaseLink
  application: m4-app
  target: demo
  releaseStrategy: m4-strategy
